# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Window(object):
    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(1834, 1052)
        self.centralwidget = QtWidgets.QWidget(Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_AI = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_AI.setEnabled(True)
        self.tabWidget_AI.setGeometry(QtCore.QRect(1430, 20, 401, 991))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_AI.sizePolicy().hasHeightForWidth())
        self.tabWidget_AI.setSizePolicy(sizePolicy)
        self.tabWidget_AI.setMinimumSize(QtCore.QSize(300, 800))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tabWidget_AI.setFont(font)
        self.tabWidget_AI.setObjectName("tabWidget_AI")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.toolButton_Start_RS = QtWidgets.QToolButton(self.tab_9)
        self.toolButton_Start_RS.setGeometry(QtCore.QRect(30, 50, 141, 51))
        self.toolButton_Start_RS.setObjectName("toolButton_Start_RS")
        self.toolButton_Stop_RS = QtWidgets.QToolButton(self.tab_9)
        self.toolButton_Stop_RS.setGeometry(QtCore.QRect(190, 50, 141, 51))
        self.toolButton_Stop_RS.setObjectName("toolButton_Stop_RS")
        self.toolButton_Play_RS = QtWidgets.QToolButton(self.tab_9)
        self.toolButton_Play_RS.setGeometry(QtCore.QRect(30, 120, 141, 51))
        self.toolButton_Play_RS.setObjectName("toolButton_Play_RS")
        self.toolButton_Cali_RS = QtWidgets.QToolButton(self.tab_9)
        self.toolButton_Cali_RS.setGeometry(QtCore.QRect(30, 260, 141, 51))
        self.toolButton_Cali_RS.setObjectName("toolButton_Cali_RS")
        self.toolButton_Grab_RS = QtWidgets.QToolButton(self.tab_9)
        self.toolButton_Grab_RS.setGeometry(QtCore.QRect(190, 120, 141, 51))
        self.toolButton_Grab_RS.setObjectName("toolButton_Grab_RS")
        self.toolButton_Save_RS = QtWidgets.QToolButton(self.tab_9)
        self.toolButton_Save_RS.setGeometry(QtCore.QRect(30, 190, 141, 51))
        self.toolButton_Save_RS.setObjectName("toolButton_Save_RS")
        self.lineEdit_Save_Prefix = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_Save_Prefix.setGeometry(QtCore.QRect(190, 190, 141, 51))
        self.lineEdit_Save_Prefix.setObjectName("lineEdit_Save_Prefix")
        self.tabWidget_AI.addTab(self.tab_9, "")
        self.tab_AI = QtWidgets.QWidget()
        self.tab_AI.setObjectName("tab_AI")
        self.label_39 = QtWidgets.QLabel(self.tab_AI)
        self.label_39.setGeometry(QtCore.QRect(30, 30, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.pushButton_Load_Image_AI = QtWidgets.QPushButton(self.tab_AI)
        self.pushButton_Load_Image_AI.setGeometry(QtCore.QRect(30, 80, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_Load_Image_AI.setFont(font)
        self.pushButton_Load_Image_AI.setObjectName("pushButton_Load_Image_AI")
        self.pushButton_Yolo_Detect = QtWidgets.QPushButton(self.tab_AI)
        self.pushButton_Yolo_Detect.setGeometry(QtCore.QRect(30, 140, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_Yolo_Detect.setFont(font)
        self.pushButton_Yolo_Detect.setObjectName("pushButton_Yolo_Detect")
        self.pushButton_Load_YOLO_Model = QtWidgets.QPushButton(self.tab_AI)
        self.pushButton_Load_YOLO_Model.setGeometry(QtCore.QRect(190, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_Load_YOLO_Model.setFont(font)
        self.pushButton_Load_YOLO_Model.setObjectName("pushButton_Load_YOLO_Model")
        self.textEdit_Info = QtWidgets.QTextEdit(self.tab_AI)
        self.textEdit_Info.setGeometry(QtCore.QRect(0, 330, 371, 621))
        self.textEdit_Info.setObjectName("textEdit_Info")
        self.spinBox_Scale_AI = QtWidgets.QSpinBox(self.tab_AI)
        self.spinBox_Scale_AI.setGeometry(QtCore.QRect(270, 80, 61, 31))
        self.spinBox_Scale_AI.setMinimum(10)
        self.spinBox_Scale_AI.setMaximum(500)
        self.spinBox_Scale_AI.setSingleStep(5)
        self.spinBox_Scale_AI.setProperty("value", 100)
        self.spinBox_Scale_AI.setObjectName("spinBox_Scale_AI")
        self.label_9 = QtWidgets.QLabel(self.tab_AI)
        self.label_9.setGeometry(QtCore.QRect(370, 160, 20, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_AI)
        self.label_10.setGeometry(QtCore.QRect(40, 300, 101, 16))
        self.label_10.setObjectName("label_10")
        self.label_18 = QtWidgets.QLabel(self.tab_AI)
        self.label_18.setGeometry(QtCore.QRect(190, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_AI)
        self.label_19.setGeometry(QtCore.QRect(190, 140, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.spinBox_Scale_AI_Detected = QtWidgets.QSpinBox(self.tab_AI)
        self.spinBox_Scale_AI_Detected.setGeometry(QtCore.QRect(270, 140, 61, 31))
        self.spinBox_Scale_AI_Detected.setMinimum(10)
        self.spinBox_Scale_AI_Detected.setMaximum(500)
        self.spinBox_Scale_AI_Detected.setSingleStep(5)
        self.spinBox_Scale_AI_Detected.setProperty("value", 100)
        self.spinBox_Scale_AI_Detected.setObjectName("spinBox_Scale_AI_Detected")
        self.label_22 = QtWidgets.QLabel(self.tab_AI)
        self.label_22.setGeometry(QtCore.QRect(50, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.spinBox_Yolo_Confidence = QtWidgets.QSpinBox(self.tab_AI)
        self.spinBox_Yolo_Confidence.setGeometry(QtCore.QRect(190, 200, 61, 31))
        self.spinBox_Yolo_Confidence.setMinimum(1)
        self.spinBox_Yolo_Confidence.setMaximum(100)
        self.spinBox_Yolo_Confidence.setSingleStep(5)
        self.spinBox_Yolo_Confidence.setProperty("value", 70)
        self.spinBox_Yolo_Confidence.setObjectName("spinBox_Yolo_Confidence")
        self.label_27 = QtWidgets.QLabel(self.tab_AI)
        self.label_27.setGeometry(QtCore.QRect(50, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.spinBox_Yolo_IOU = QtWidgets.QSpinBox(self.tab_AI)
        self.spinBox_Yolo_IOU.setGeometry(QtCore.QRect(190, 240, 61, 31))
        self.spinBox_Yolo_IOU.setMinimum(1)
        self.spinBox_Yolo_IOU.setMaximum(100)
        self.spinBox_Yolo_IOU.setSingleStep(5)
        self.spinBox_Yolo_IOU.setProperty("value", 30)
        self.spinBox_Yolo_IOU.setObjectName("spinBox_Yolo_IOU")
        self.label_28 = QtWidgets.QLabel(self.tab_AI)
        self.label_28.setGeometry(QtCore.QRect(260, 200, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_AI)
        self.label_29.setGeometry(QtCore.QRect(260, 240, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.tabWidget_AI.addTab(self.tab_AI, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 210, 331, 191))
        self.groupBox.setObjectName("groupBox")
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(30, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(130, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(230, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lineEdit_H_Min = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_H_Min.setGeometry(QtCore.QRect(30, 70, 51, 31))
        self.lineEdit_H_Min.setObjectName("lineEdit_H_Min")
        self.lineEdit_S_Min = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_S_Min.setGeometry(QtCore.QRect(130, 70, 51, 31))
        self.lineEdit_S_Min.setObjectName("lineEdit_S_Min")
        self.lineEdit_V_Min = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_V_Min.setGeometry(QtCore.QRect(230, 70, 51, 31))
        self.lineEdit_V_Min.setObjectName("lineEdit_V_Min")
        self.lineEdit_H_Max = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_H_Max.setGeometry(QtCore.QRect(30, 140, 51, 31))
        self.lineEdit_H_Max.setObjectName("lineEdit_H_Max")
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(130, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setGeometry(QtCore.QRect(230, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.lineEdit_S_Max = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_S_Max.setGeometry(QtCore.QRect(130, 140, 51, 31))
        self.lineEdit_S_Max.setObjectName("lineEdit_S_Max")
        self.lineEdit_V_Max = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_V_Max.setGeometry(QtCore.QRect(230, 140, 51, 31))
        self.lineEdit_V_Max.setObjectName("lineEdit_V_Max")
        self.label_36 = QtWidgets.QLabel(self.groupBox)
        self.label_36.setGeometry(QtCore.QRect(30, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(200, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.pushButton_Load_Image_Color = QtWidgets.QPushButton(self.tab)
        self.pushButton_Load_Image_Color.setGeometry(QtCore.QRect(40, 30, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton_Load_Image_Color.setFont(font)
        self.pushButton_Load_Image_Color.setObjectName("pushButton_Load_Image_Color")
        self.spinBox_Scale_Color = QtWidgets.QSpinBox(self.tab)
        self.spinBox_Scale_Color.setGeometry(QtCore.QRect(280, 30, 61, 31))
        self.spinBox_Scale_Color.setMinimum(10)
        self.spinBox_Scale_Color.setMaximum(500)
        self.spinBox_Scale_Color.setSingleStep(5)
        self.spinBox_Scale_Color.setProperty("value", 100)
        self.spinBox_Scale_Color.setObjectName("spinBox_Scale_Color")
        self.textEdit_Color = QtWidgets.QTextEdit(self.tab)
        self.textEdit_Color.setGeometry(QtCore.QRect(30, 600, 331, 331))
        self.textEdit_Color.setObjectName("textEdit_Color")
        self.pushButton_Color_Track = QtWidgets.QPushButton(self.tab)
        self.pushButton_Color_Track.setGeometry(QtCore.QRect(40, 90, 141, 41))
        self.pushButton_Color_Track.setObjectName("pushButton_Color_Track")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 400, 331, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(30, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(130, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(230, 40, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.lineEdit_R_Min = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_R_Min.setGeometry(QtCore.QRect(30, 70, 51, 31))
        self.lineEdit_R_Min.setObjectName("lineEdit_R_Min")
        self.lineEdit_G_Min = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_G_Min.setGeometry(QtCore.QRect(130, 70, 51, 31))
        self.lineEdit_G_Min.setObjectName("lineEdit_G_Min")
        self.lineEdit_B_Min = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_B_Min.setGeometry(QtCore.QRect(230, 70, 51, 31))
        self.lineEdit_B_Min.setObjectName("lineEdit_B_Min")
        self.lineEdit_R_Max = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_R_Max.setGeometry(QtCore.QRect(30, 140, 51, 31))
        self.lineEdit_R_Max.setObjectName("lineEdit_R_Max")
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setGeometry(QtCore.QRect(130, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        self.label_42.setGeometry(QtCore.QRect(230, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.lineEdit_G_Max = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_G_Max.setGeometry(QtCore.QRect(130, 140, 51, 31))
        self.lineEdit_G_Max.setObjectName("lineEdit_G_Max")
        self.lineEdit_B_Max = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_B_Max.setGeometry(QtCore.QRect(230, 140, 51, 31))
        self.lineEdit_B_Max.setObjectName("lineEdit_B_Max")
        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        self.label_43.setGeometry(QtCore.QRect(30, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.lineEdit_R = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_R.setGeometry(QtCore.QRect(190, 100, 51, 31))
        self.lineEdit_R.setObjectName("lineEdit_R")
        self.lineEdit_G = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_G.setGeometry(QtCore.QRect(250, 100, 51, 31))
        self.lineEdit_G.setObjectName("lineEdit_G")
        self.lineEdit_B = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_B.setGeometry(QtCore.QRect(310, 100, 51, 31))
        self.lineEdit_B.setObjectName("lineEdit_B")
        self.lineEdit_V = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_V.setGeometry(QtCore.QRect(310, 160, 51, 31))
        self.lineEdit_V.setObjectName("lineEdit_V")
        self.lineEdit_H = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_H.setGeometry(QtCore.QRect(190, 160, 51, 31))
        self.lineEdit_H.setObjectName("lineEdit_H")
        self.lineEdit_S = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_S.setGeometry(QtCore.QRect(250, 160, 51, 31))
        self.lineEdit_S.setObjectName("lineEdit_S")
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setGeometry(QtCore.QRect(190, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab)
        self.label_45.setGeometry(QtCore.QRect(190, 130, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.pushButton_Color_Collect = QtWidgets.QPushButton(self.tab)
        self.pushButton_Color_Collect.setGeometry(QtCore.QRect(40, 150, 141, 41))
        self.pushButton_Color_Collect.setObjectName("pushButton_Color_Collect")
        self.tabWidget_AI.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton_Select_Data_Folder = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_Select_Data_Folder.setGeometry(QtCore.QRect(10, 40, 141, 41))
        self.pushButton_Select_Data_Folder.setObjectName("pushButton_Select_Data_Folder")
        self.lineEdit_Data_Dir = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_Data_Dir.setGeometry(QtCore.QRect(170, 40, 211, 41))
        self.lineEdit_Data_Dir.setObjectName("lineEdit_Data_Dir")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(20, 110, 201, 16))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 100, 351, 151))
        self.groupBox_7.setObjectName("groupBox_7")
        self.checkBox_Flip_Horizontal = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_Flip_Horizontal.setGeometry(QtCore.QRect(40, 30, 131, 31))
        self.checkBox_Flip_Horizontal.setObjectName("checkBox_Flip_Horizontal")
        self.checkBox_Flip_Vertical = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_Flip_Vertical.setGeometry(QtCore.QRect(170, 30, 131, 31))
        self.checkBox_Flip_Vertical.setObjectName("checkBox_Flip_Vertical")
        self.checkBox_Brighten = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_Brighten.setGeometry(QtCore.QRect(40, 70, 131, 31))
        self.checkBox_Brighten.setObjectName("checkBox_Brighten")
        self.checkBox_Darken = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_Darken.setGeometry(QtCore.QRect(170, 70, 131, 31))
        self.checkBox_Darken.setObjectName("checkBox_Darken")
        self.checkBox_Blur = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_Blur.setGeometry(QtCore.QRect(40, 110, 131, 31))
        self.checkBox_Blur.setObjectName("checkBox_Blur")
        self.checkBox_Shapen = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_Shapen.setGeometry(QtCore.QRect(170, 110, 131, 31))
        self.checkBox_Shapen.setObjectName("checkBox_Shapen")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(20, 270, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.comboBox_ResNetType = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_ResNetType.setGeometry(QtCore.QRect(180, 270, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_ResNetType.setFont(font)
        self.comboBox_ResNetType.setObjectName("comboBox_ResNetType")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 320, 351, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(30, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit_Image_Size_Row = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_Image_Size_Row.setGeometry(QtCore.QRect(130, 40, 61, 31))
        self.lineEdit_Image_Size_Row.setObjectName("lineEdit_Image_Size_Row")
        self.lineEdit_Image_Size_Col = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_Image_Size_Col.setGeometry(QtCore.QRect(220, 40, 61, 31))
        self.lineEdit_Image_Size_Col.setObjectName("lineEdit_Image_Size_Col")
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(200, 40, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(30, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.spinBox_No_Epoch = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_No_Epoch.setGeometry(QtCore.QRect(210, 90, 111, 31))
        self.spinBox_No_Epoch.setMinimum(1)
        self.spinBox_No_Epoch.setMaximum(100000)
        self.spinBox_No_Epoch.setSingleStep(5)
        self.spinBox_No_Epoch.setProperty("value", 20)
        self.spinBox_No_Epoch.setObjectName("spinBox_No_Epoch")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(30, 140, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.spinBox_Batch_Size = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_Batch_Size.setGeometry(QtCore.QRect(240, 140, 81, 31))
        self.spinBox_Batch_Size.setMinimum(1)
        self.spinBox_Batch_Size.setMaximum(100000)
        self.spinBox_Batch_Size.setSingleStep(5)
        self.spinBox_Batch_Size.setProperty("value", 20)
        self.spinBox_Batch_Size.setObjectName("spinBox_Batch_Size")
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(30, 180, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.lineEdit_Learning_Rate = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_Learning_Rate.setGeometry(QtCore.QRect(250, 180, 71, 31))
        self.lineEdit_Learning_Rate.setObjectName("lineEdit_Learning_Rate")
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setGeometry(QtCore.QRect(20, 600, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lineEdit_Model_Name = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_Model_Name.setGeometry(QtCore.QRect(190, 600, 161, 31))
        self.lineEdit_Model_Name.setText("")
        self.lineEdit_Model_Name.setObjectName("lineEdit_Model_Name")
        self.pushButton_Train_ResNet = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_Train_ResNet.setGeometry(QtCore.QRect(190, 660, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_Train_ResNet.setFont(font)
        self.pushButton_Train_ResNet.setObjectName("pushButton_Train_ResNet")
        self.tabWidget_AI.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 30, 351, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_Live = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_Live.setGeometry(QtCore.QRect(30, 40, 121, 41))
        self.pushButton_Live.setObjectName("pushButton_Live")
        self.pushButton_Grab = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_Grab.setGeometry(QtCore.QRect(190, 40, 111, 41))
        self.pushButton_Grab.setObjectName("pushButton_Grab")
        self.pushButton_ExtTrigger = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_ExtTrigger.setGeometry(QtCore.QRect(30, 100, 121, 41))
        self.pushButton_ExtTrigger.setObjectName("pushButton_ExtTrigger")
        self.pushButton_SoftTrigger = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_SoftTrigger.setGeometry(QtCore.QRect(190, 100, 111, 41))
        self.pushButton_SoftTrigger.setObjectName("pushButton_SoftTrigger")
        self.pushButton_Save = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_Save.setGeometry(QtCore.QRect(30, 160, 121, 41))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 260, 351, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(30, 40, 121, 16))
        self.label_23.setObjectName("label_23")
        self.spinBox_FrameRate = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_FrameRate.setGeometry(QtCore.QRect(190, 30, 101, 31))
        self.spinBox_FrameRate.setMinimum(1)
        self.spinBox_FrameRate.setMaximum(150)
        self.spinBox_FrameRate.setSingleStep(1)
        self.spinBox_FrameRate.setProperty("value", 30)
        self.spinBox_FrameRate.setObjectName("spinBox_FrameRate")
        self.spinBox_Exposure = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_Exposure.setGeometry(QtCore.QRect(190, 70, 101, 31))
        self.spinBox_Exposure.setMinimum(1)
        self.spinBox_Exposure.setMaximum(1000000)
        self.spinBox_Exposure.setSingleStep(10)
        self.spinBox_Exposure.setProperty("value", 4250)
        self.spinBox_Exposure.setObjectName("spinBox_Exposure")
        self.label_24 = QtWidgets.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(30, 80, 121, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(300, 80, 41, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(300, 40, 41, 16))
        self.label_26.setObjectName("label_26")
        self.tabWidget_AI.addTab(self.tab_4, "")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 10, 71, 971))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.toolButton_Brighten = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_Brighten.setGeometry(QtCore.QRect(0, 50, 61, 51))
        self.toolButton_Brighten.setObjectName("toolButton_Brighten")
        self.toolButton_Darken = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_Darken.setGeometry(QtCore.QRect(0, 100, 61, 51))
        self.toolButton_Darken.setObjectName("toolButton_Darken")
        self.toolButton_Blur = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_Blur.setGeometry(QtCore.QRect(0, 150, 61, 51))
        self.toolButton_Blur.setObjectName("toolButton_Blur")
        self.toolButton_Sharp = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_Sharp.setGeometry(QtCore.QRect(0, 200, 61, 51))
        self.toolButton_Sharp.setObjectName("toolButton_Sharp")
        self.toolButton_Flip_H = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_Flip_H.setGeometry(QtCore.QRect(0, 250, 61, 51))
        self.toolButton_Flip_H.setObjectName("toolButton_Flip_H")
        self.toolButton_Flip_V = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_Flip_V.setGeometry(QtCore.QRect(0, 300, 61, 51))
        self.toolButton_Flip_V.setObjectName("toolButton_Flip_V")
        self.toolButton_Load = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_Load.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.toolButton_Load.setObjectName("toolButton_Load")
        self.toolButton_Save = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_Save.setGeometry(QtCore.QRect(0, 350, 61, 51))
        self.toolButton_Save.setObjectName("toolButton_Save")
        self.toolButton_Save_as = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_Save_as.setGeometry(QtCore.QRect(0, 400, 61, 51))
        self.toolButton_Save_as.setObjectName("toolButton_Save_as")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(60, 0, 1371, 991))
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_10)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 661, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(1, 1))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setObjectName("formLayout")
        self.label_Image_Color = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Image_Color.sizePolicy().hasHeightForWidth())
        self.label_Image_Color.setSizePolicy(sizePolicy)
        self.label_Image_Color.setMinimumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Image_Color.setFont(font)
        self.label_Image_Color.setMouseTracking(True)
        self.label_Image_Color.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Image_Color.setText("")
        self.label_Image_Color.setPixmap(QtGui.QPixmap("aoi.jpg"))
        self.label_Image_Color.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image_Color.setObjectName("label_Image_Color")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_Image_Color)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_depth = QtWidgets.QScrollArea(self.tab_10)
        self.scrollArea_depth.setGeometry(QtCore.QRect(670, 0, 661, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_depth.sizePolicy().hasHeightForWidth())
        self.scrollArea_depth.setSizePolicy(sizePolicy)
        self.scrollArea_depth.setMinimumSize(QtCore.QSize(1, 1))
        self.scrollArea_depth.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_depth.setWidgetResizable(True)
        self.scrollArea_depth.setObjectName("scrollArea_depth")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 659, 489))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_4)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(2, 2, 2, 2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_Image_Depth = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Image_Depth.sizePolicy().hasHeightForWidth())
        self.label_Image_Depth.setSizePolicy(sizePolicy)
        self.label_Image_Depth.setMinimumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Image_Depth.setFont(font)
        self.label_Image_Depth.setMouseTracking(True)
        self.label_Image_Depth.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Image_Depth.setText("")
        self.label_Image_Depth.setPixmap(QtGui.QPixmap("aoi.jpg"))
        self.label_Image_Depth.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image_Depth.setObjectName("label_Image_Depth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_Image_Depth)
        self.scrollArea_depth.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_10)
        self.scrollArea_5.setGeometry(QtCore.QRect(670, 490, 661, 481))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 659, 479))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.scrollArea_IR = QtWidgets.QScrollArea(self.tab_10)
        self.scrollArea_IR.setGeometry(QtCore.QRect(0, 490, 661, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_IR.sizePolicy().hasHeightForWidth())
        self.scrollArea_IR.setSizePolicy(sizePolicy)
        self.scrollArea_IR.setMinimumSize(QtCore.QSize(1, 1))
        self.scrollArea_IR.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_IR.setWidgetResizable(True)
        self.scrollArea_IR.setObjectName("scrollArea_IR")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 659, 489))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.formLayout_4 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_5)
        self.formLayout_4.setContentsMargins(2, 2, 2, 2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_Image_IR = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Image_IR.sizePolicy().hasHeightForWidth())
        self.label_Image_IR.setSizePolicy(sizePolicy)
        self.label_Image_IR.setMinimumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Image_IR.setFont(font)
        self.label_Image_IR.setMouseTracking(True)
        self.label_Image_IR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Image_IR.setText("")
        self.label_Image_IR.setPixmap(QtGui.QPixmap("aoi.jpg"))
        self.label_Image_IR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image_IR.setObjectName("label_Image_IR")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_Image_IR)
        self.scrollArea_IR.setWidget(self.scrollAreaWidgetContents_5)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab_11)
        self.scrollArea_6.setGeometry(QtCore.QRect(0, 10, 1331, 971))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setMinimumSize(QtCore.QSize(1, 1))
        self.scrollArea_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 1329, 969))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.formLayout_3 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents_7)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_Image = QtWidgets.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Image.sizePolicy().hasHeightForWidth())
        self.label_Image.setSizePolicy(sizePolicy)
        self.label_Image.setMinimumSize(QtCore.QSize(1024, 768))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Image.setFont(font)
        self.label_Image.setMouseTracking(True)
        self.label_Image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_Image.setText("")
        self.label_Image.setPixmap(QtGui.QPixmap("aoi.jpg"))
        self.label_Image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image.setObjectName("label_Image")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Image)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_7)
        self.tabWidget_2.addTab(self.tab_11, "")
        Main_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1834, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp_2 = QtWidgets.QMenu(self.menubar)
        self.menuHelp_2.setObjectName("menuHelp_2")
        self.menuFlip_2 = QtWidgets.QMenu(self.menuHelp_2)
        self.menuFlip_2.setObjectName("menuFlip_2")
        self.menuRotate_2 = QtWidgets.QMenu(self.menuHelp_2)
        self.menuRotate_2.setObjectName("menuRotate_2")
        self.menuHelp_3 = QtWidgets.QMenu(self.menubar)
        self.menuHelp_3.setObjectName("menuHelp_3")
        self.menuSegment = QtWidgets.QMenu(self.menubar)
        self.menuSegment.setObjectName("menuSegment")
        self.menuThreshold = QtWidgets.QMenu(self.menuSegment)
        self.menuThreshold.setObjectName("menuThreshold")
        Main_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main_Window)
        self.statusbar.setObjectName("statusbar")
        Main_Window.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(Main_Window)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtWidgets.QAction(Main_Window)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Image = QtWidgets.QAction(Main_Window)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionBrighten = QtWidgets.QAction(Main_Window)
        self.actionBrighten.setObjectName("actionBrighten")
        self.actionDarken = QtWidgets.QAction(Main_Window)
        self.actionDarken.setObjectName("actionDarken")
        self.actionBlur = QtWidgets.QAction(Main_Window)
        self.actionBlur.setObjectName("actionBlur")
        self.actionSharp = QtWidgets.QAction(Main_Window)
        self.actionSharp.setObjectName("actionSharp")
        self.actionHorizontal = QtWidgets.QAction(Main_Window)
        self.actionHorizontal.setObjectName("actionHorizontal")
        self.actionVertical = QtWidgets.QAction(Main_Window)
        self.actionVertical.setObjectName("actionVertical")
        self.actionBoth_H_and_V = QtWidgets.QAction(Main_Window)
        self.actionBoth_H_and_V.setObjectName("actionBoth_H_and_V")
        self.action30 = QtWidgets.QAction(Main_Window)
        self.action30.setObjectName("action30")
        self.action60_degree = QtWidgets.QAction(Main_Window)
        self.action60_degree.setObjectName("action60_degree")
        self.action45_degree = QtWidgets.QAction(Main_Window)
        self.action45_degree.setObjectName("action45_degree")
        self.actionSave_as = QtWidgets.QAction(Main_Window)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionHorizontal_2 = QtWidgets.QAction(Main_Window)
        self.actionHorizontal_2.setObjectName("actionHorizontal_2")
        self.actionVertical_2 = QtWidgets.QAction(Main_Window)
        self.actionVertical_2.setObjectName("actionVertical_2")
        self.actionHorizontal_Vertical = QtWidgets.QAction(Main_Window)
        self.actionHorizontal_Vertical.setObjectName("actionHorizontal_Vertical")
        self.action30_degree = QtWidgets.QAction(Main_Window)
        self.action30_degree.setObjectName("action30_degree")
        self.action60_degree_2 = QtWidgets.QAction(Main_Window)
        self.action60_degree_2.setObjectName("action60_degree_2")
        self.action45_degree_2 = QtWidgets.QAction(Main_Window)
        self.action45_degree_2.setObjectName("action45_degree_2")
        self.action90_degree = QtWidgets.QAction(Main_Window)
        self.action90_degree.setObjectName("action90_degree")
        self.action180_degree = QtWidgets.QAction(Main_Window)
        self.action180_degree.setObjectName("action180_degree")
        self.actionOtsu_method = QtWidgets.QAction(Main_Window)
        self.actionOtsu_method.setObjectName("actionOtsu_method")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionBrighten)
        self.menuHelp.addAction(self.actionDarken)
        self.menuHelp.addAction(self.actionBlur)
        self.menuHelp.addAction(self.actionSharp)
        self.menuHelp.addSeparator()
        self.menuHelp.addSeparator()
        self.menuFlip_2.addAction(self.actionHorizontal_2)
        self.menuFlip_2.addAction(self.actionVertical_2)
        self.menuFlip_2.addAction(self.actionHorizontal_Vertical)
        self.menuRotate_2.addAction(self.action30_degree)
        self.menuRotate_2.addAction(self.action45_degree_2)
        self.menuRotate_2.addAction(self.action60_degree_2)
        self.menuRotate_2.addAction(self.action90_degree)
        self.menuRotate_2.addAction(self.action180_degree)
        self.menuHelp_2.addAction(self.menuFlip_2.menuAction())
        self.menuHelp_2.addAction(self.menuRotate_2.menuAction())
        self.menuThreshold.addAction(self.actionOtsu_method)
        self.menuSegment.addAction(self.menuThreshold.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSegment.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuHelp_2.menuAction())
        self.menubar.addAction(self.menuHelp_3.menuAction())

        self.retranslateUi(Main_Window)
        self.tabWidget_AI.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "MainWindow"))
        self.toolButton_Start_RS.setText(_translate("Main_Window", "Start CAM"))
        self.toolButton_Stop_RS.setText(_translate("Main_Window", "Stop CAM"))
        self.toolButton_Play_RS.setText(_translate("Main_Window", "Play"))
        self.toolButton_Cali_RS.setText(_translate("Main_Window", "偵測"))
        self.toolButton_Grab_RS.setText(_translate("Main_Window", "Grab"))
        self.toolButton_Save_RS.setText(_translate("Main_Window", "Save"))
        self.lineEdit_Save_Prefix.setText(_translate("Main_Window", "Img"))
        self.tabWidget_AI.setTabText(self.tabWidget_AI.indexOf(self.tab_9), _translate("Main_Window", "RealSense"))
        self.label_39.setText(_translate("Main_Window", "選擇 YOLO Model"))
        self.pushButton_Load_Image_AI.setText(_translate("Main_Window", "開啟影像"))
        self.pushButton_Yolo_Detect.setText(_translate("Main_Window", "自動偵測"))
        self.pushButton_Load_YOLO_Model.setText(_translate("Main_Window", "載入Model"))
        self.label_9.setText(_translate("Main_Window", "%"))
        self.label_10.setText(_translate("Main_Window", "Information"))
        self.label_18.setText(_translate("Main_Window", "影像大小"))
        self.label_19.setText(_translate("Main_Window", "影像大小"))
        self.label_22.setText(_translate("Main_Window", "Confidence"))
        self.label_27.setText(_translate("Main_Window", "IoU"))
        self.label_28.setText(_translate("Main_Window", "%"))
        self.label_29.setText(_translate("Main_Window", "%"))
        self.tabWidget_AI.setTabText(self.tabWidget_AI.indexOf(self.tab_AI), _translate("Main_Window", "YOLO-Predict"))
        self.groupBox.setTitle(_translate("Main_Window", "  HSV Color Ranges  "))
        self.label_31.setText(_translate("Main_Window", "H_min"))
        self.label_32.setText(_translate("Main_Window", "S_min"))
        self.label_33.setText(_translate("Main_Window", "V_min"))
        self.label_34.setText(_translate("Main_Window", "S_max"))
        self.label_35.setText(_translate("Main_Window", "V_max"))
        self.label_36.setText(_translate("Main_Window", "H_max"))
        self.label_30.setText(_translate("Main_Window", "影像大小"))
        self.pushButton_Load_Image_Color.setText(_translate("Main_Window", "開啟影像"))
        self.pushButton_Color_Track.setText(_translate("Main_Window", "Start"))
        self.groupBox_2.setTitle(_translate("Main_Window", "  RGB Color Ranges  "))
        self.label_37.setText(_translate("Main_Window", "R_min"))
        self.label_38.setText(_translate("Main_Window", "G_min"))
        self.label_40.setText(_translate("Main_Window", "B_min"))
        self.label_41.setText(_translate("Main_Window", "G_max"))
        self.label_42.setText(_translate("Main_Window", "B_max"))
        self.label_43.setText(_translate("Main_Window", "R_max"))
        self.label_44.setText(_translate("Main_Window", "RGB"))
        self.label_45.setText(_translate("Main_Window", "HSV"))
        self.pushButton_Color_Collect.setText(_translate("Main_Window", "Collect (click)"))
        self.tabWidget_AI.setTabText(self.tabWidget_AI.indexOf(self.tab), _translate("Main_Window", "Color Extract"))
        self.pushButton_Select_Data_Folder.setText(_translate("Main_Window", "設定訓練資料夾"))
        self.groupBox_7.setTitle(_translate("Main_Window", " 資料增益 (Data Augment)  "))
        self.checkBox_Flip_Horizontal.setText(_translate("Main_Window", " 水平翻轉"))
        self.checkBox_Flip_Vertical.setText(_translate("Main_Window", " 垂直翻轉"))
        self.checkBox_Brighten.setText(_translate("Main_Window", "影像變亮"))
        self.checkBox_Darken.setText(_translate("Main_Window", "影像變暗"))
        self.checkBox_Blur.setText(_translate("Main_Window", "影像模糊化"))
        self.checkBox_Shapen.setText(_translate("Main_Window", "影像銳利化"))
        self.label_13.setText(_translate("Main_Window", "選擇訓練網路"))
        self.groupBox_8.setTitle(_translate("Main_Window", " 訓練參數  "))
        self.label_14.setText(_translate("Main_Window", "影像大小"))
        self.lineEdit_Image_Size_Row.setText(_translate("Main_Window", "256"))
        self.lineEdit_Image_Size_Col.setText(_translate("Main_Window", "256"))
        self.label_15.setText(_translate("Main_Window", "x"))
        self.label_16.setText(_translate("Main_Window", "訓練次數"))
        self.label_17.setText(_translate("Main_Window", "批次量(batch size)"))
        self.label_21.setText(_translate("Main_Window", "學習率 (Learning Rate)"))
        self.lineEdit_Learning_Rate.setText(_translate("Main_Window", "0.01"))
        self.label_20.setText(_translate("Main_Window", "儲存Model 名稱"))
        self.pushButton_Train_ResNet.setText(_translate("Main_Window", "開始訓練"))
        self.tabWidget_AI.setTabText(self.tabWidget_AI.indexOf(self.tab_5), _translate("Main_Window", "ResNet-Train"))
        self.groupBox_4.setTitle(_translate("Main_Window", "   CCD Acquistion  "))
        self.pushButton_Live.setText(_translate("Main_Window", "Live"))
        self.pushButton_Grab.setText(_translate("Main_Window", "Grab"))
        self.pushButton_ExtTrigger.setText(_translate("Main_Window", "Ext Trigger"))
        self.pushButton_SoftTrigger.setText(_translate("Main_Window", "SoftTrigger"))
        self.pushButton_Save.setText(_translate("Main_Window", "Save Image"))
        self.groupBox_5.setTitle(_translate("Main_Window", "  CCD Params Setup  "))
        self.label_23.setText(_translate("Main_Window", "Frame Rate"))
        self.label_24.setText(_translate("Main_Window", "Exposure"))
        self.label_25.setText(_translate("Main_Window", "ms"))
        self.label_26.setText(_translate("Main_Window", "fps"))
        self.tabWidget_AI.setTabText(self.tabWidget_AI.indexOf(self.tab_4), _translate("Main_Window", "CCD"))
        self.toolButton_Brighten.setText(_translate("Main_Window", "Bright"))
        self.toolButton_Darken.setText(_translate("Main_Window", "Dark"))
        self.toolButton_Blur.setText(_translate("Main_Window", "Blur"))
        self.toolButton_Sharp.setText(_translate("Main_Window", "Sharp"))
        self.toolButton_Flip_H.setText(_translate("Main_Window", "Flip H"))
        self.toolButton_Flip_V.setText(_translate("Main_Window", "Flip V"))
        self.toolButton_Load.setText(_translate("Main_Window", "Load"))
        self.toolButton_Save.setText(_translate("Main_Window", "Save"))
        self.toolButton_Save_as.setText(_translate("Main_Window", "Save as"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("Main_Window", "RealSense"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("Main_Window", "YOLOv5"))
        self.menuFile.setTitle(_translate("Main_Window", "File"))
        self.menuHelp.setTitle(_translate("Main_Window", "Enhance"))
        self.menuHelp_2.setTitle(_translate("Main_Window", "Transform"))
        self.menuFlip_2.setTitle(_translate("Main_Window", "Flip"))
        self.menuRotate_2.setTitle(_translate("Main_Window", "Rotate"))
        self.menuHelp_3.setTitle(_translate("Main_Window", "Help"))
        self.menuSegment.setTitle(_translate("Main_Window", "Segment"))
        self.menuThreshold.setTitle(_translate("Main_Window", "Threshold"))
        self.actionLoad.setText(_translate("Main_Window", "Load"))
        self.actionExit.setText(_translate("Main_Window", "Exit"))
        self.actionSave_Image.setText(_translate("Main_Window", "Save"))
        self.actionBrighten.setText(_translate("Main_Window", "Brighten"))
        self.actionDarken.setText(_translate("Main_Window", "Darken"))
        self.actionBlur.setText(_translate("Main_Window", "Blur"))
        self.actionSharp.setText(_translate("Main_Window", "Sharp"))
        self.actionHorizontal.setText(_translate("Main_Window", "Horizontal"))
        self.actionVertical.setText(_translate("Main_Window", "Vertical"))
        self.actionBoth_H_and_V.setText(_translate("Main_Window", "Both H and V"))
        self.action30.setText(_translate("Main_Window", "30 degree"))
        self.action60_degree.setText(_translate("Main_Window", "60 degree"))
        self.action45_degree.setText(_translate("Main_Window", "45 degree"))
        self.actionSave_as.setText(_translate("Main_Window", "Save as"))
        self.actionHorizontal_2.setText(_translate("Main_Window", "Horizontal"))
        self.actionVertical_2.setText(_translate("Main_Window", "Vertical"))
        self.actionHorizontal_Vertical.setText(_translate("Main_Window", "Horizontal & Vertical"))
        self.action30_degree.setText(_translate("Main_Window", "30 degree"))
        self.action60_degree_2.setText(_translate("Main_Window", "60 degree"))
        self.action45_degree_2.setText(_translate("Main_Window", "45 degree"))
        self.action90_degree.setText(_translate("Main_Window", "90 degree"))
        self.action180_degree.setText(_translate("Main_Window", "180 degree"))
        self.actionOtsu_method.setText(_translate("Main_Window", "Otsu method"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_Window = QtWidgets.QMainWindow()
    ui = Ui_Main_Window()
    ui.setupUi(Main_Window)
    Main_Window.show()
    sys.exit(app.exec_())
